package org.ismek.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2019-01-19T04:54:09.589+02:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "SakilaWebServiceImplService", 
                  wsdlLocation = "file:/C:/Java/GitWorkspace/JavaEE/Sakila/sakila/SakilaUi/src/main/java/org/ismek/client/servis.wsdl",
                  targetNamespace = "http://web.ismek.org/") 
public class SakilaWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.ismek.org/", "SakilaWebServiceImplService");
    public final static QName SakilaWebServiceImplPort = new QName("http://web.ismek.org/", "SakilaWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Java/GitWorkspace/JavaEE/Sakila/sakila/SakilaUi/src/main/java/org/ismek/client/servis.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SakilaWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Java/GitWorkspace/JavaEE/Sakila/sakila/SakilaUi/src/main/java/org/ismek/client/servis.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SakilaWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SakilaWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SakilaWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SakilaWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SakilaWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SakilaWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SakilaWebService
     */
    @WebEndpoint(name = "SakilaWebServiceImplPort")
    public SakilaWebService getSakilaWebServiceImplPort() {
        return super.getPort(SakilaWebServiceImplPort, SakilaWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SakilaWebService
     */
    @WebEndpoint(name = "SakilaWebServiceImplPort")
    public SakilaWebService getSakilaWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SakilaWebServiceImplPort, SakilaWebService.class, features);
    }

}
