package org.ismek.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2019-01-19T04:54:09.563+02:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://web.ismek.org/", name = "SakilaWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface SakilaWebService {

    @WebMethod
    @Action(input = "http://web.ismek.org/SakilaWebService/findAllFilmListRequest", output = "http://web.ismek.org/SakilaWebService/findAllFilmListResponse")
    @RequestWrapper(localName = "findAllFilmList", targetNamespace = "http://web.ismek.org/", className = "org.ismek.client.FindAllFilmList")
    @ResponseWrapper(localName = "findAllFilmListResponse", targetNamespace = "http://web.ismek.org/", className = "org.ismek.client.FindAllFilmListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.ismek.client.SakilaFilmDto> findAllFilmList();
}
